### ISSUE TITLE
It is taking a lot of time to show updated changes in code

### ISSUE THREAD

**Issue by manibha-jain** [domdomegg/serverless-offline-watcher#2]
I used the plugin to detect changes in a file , my code is as follows:
```
plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-offline-watcher

  serverless-offline-watcher: 
    - path: api_results/handler.py
      command: echo "index.ts was modified!"
```
after making changes and saving the file it shows me `index.ts was modified` but when I run the function from that file it takes more than 1-2 min to show me the updated changes.Sometimes even more than 5 min and sometimes immediately. Why is that?

My serverless framework version :-
Framework Core: 3.22.0
Plugin: 6.2.2
SDK: 4.3.2
